try(func() {
    show.log("Executing function block");
}, func(error) {
    show.log("Error: " + string(error));
});